version: "3.4"

services:
  horiokart:
    image: horiokart
    build:
      context: "./"
      dockerfile: "docker/Dockerfile.noetic"
    network_mode: "host"
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app/horiokart/
      - type: bind
        source: ${HOME}/ros_data
        target: /root/ros_data
      - type: bind
        source: /dev
        target: /dev
    command: "/app/horiokart/docker/docker-entrypoint.sh"
