version: "3.4"

services:
  horiokart:
    image: horiokart
    build:
      context: "./"
      dockerfile: "docker/Dockerfile"
    network_mode: "host"
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
      PYTHONUNBUFFERED: 1
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /app/horiokart/
    command: "/app/org/docker/docker-entrypoint.sh"