scan_filter_chain:
  ros__parameters:
    filter1:
      name: angle1
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle:  -1.57
        upper_angle:  1.57
